name: Close Pull Request

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]
    branches: [ dev ]

jobs:
  merge_job:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Checkout the code in the pull request
      - name: 'Checkout source code'
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true

      - name: Check on failures
        if: steps.changed-files.outcome != 'success'
        run: |
          echo You must update your branch with dev
          exit 1  
      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
            wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
            mkdir ~/sfdx
            tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
            export PATH=~/sfdx/bin:$PATH
            PATH=~/sfdx/bin:$PATH
            rm sfdx-linux-x64.tar.xz
            echo sfdx installed succesfully
            echo $PATH
    

  close_job:
    # this job will only run if the PR has been closed without being merged
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo PR #${{ github.event.number }} has been closed without being merged
